### ISSUE TITLE
ReferenceError: Set is not defined

### ISSUE THREAD

**Issue by fabbrikk** [yanatan16/gulp-packer#1]
Using laravel elixir:

var gulp = require('gulp');
var packer = require('gulp-packer');
var streamify = require('gulp-streamify');
var elixir = require('laravel-elixir');

gulp.task('js', function() {
  gulp.src('/public/js/*.js')
    .pipe(streamify(packer({base62: true, shrink: true})))
    .pipe(gulp.dest('/public/build/js'))
});
elixir(function(mix) {
    mix.task('js');
});

I got this error:

ReferenceError: Set is not defined
    at Object.<anonymous> (/Volumes/hdd/project/remote/node_modules/gulp-packer/node_modules/packer/node_modules/jsdom/lib/jsdom/level2/html.js:405:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/hdd/project/remote/node_modules/gulp-packer/node_modules/packer/node_modules/jsdom/lib/jsdom/living/index.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by yanatan16** [comment]
This might be related to #3 Try version `0.1.2`

**Comment by fabbrikk** [comment]
Yes. It was a version related problem.
